# This Dockerfile is used to build a Docker image for a Python application using Uvicorn as the ASGI server. It starts from the official Python 3.12 slim image, sets the working directory to /app, and copies the requirements.txt file into the container. It then updates the package lists, upgrades installed packages, cleans up unnecessary files, and installs the required Python packages listed in requirements.txt. Finally, it copies the rest of the application code into the container, exposes port 8000 for incoming traffic, and specifies the command to run the Uvicorn server when the container starts.

FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]