name: CD

on:
    workflow_call:
        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy to EC2
              uses: appleboy/ssh-action@v0.1.5
              with:
                    host: ${{secrets.EC2_HOST}}
                    username: ${{secrets.EC2_USERNAME}}
                    key: ${{secrets.EC2_SSH_KEY}}

                    script: |
                        cd ~/secureshare
                        git pull origin main    
                        docker compose down
                        docker compose build --no-cache
                        docker compose up -d
                        docker compose ps